# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
use_frameworks!

target 'ChatKit_Example' do
  pod 'ChatKit', :path => '../'
  pod 'pop', '~> 1.0'
  pod 'DTCoreText', '~> 1.6'
  pod 'GRMustache', '~> 7.3'
  pod 'Masonry', '~> 1.1'
  pod 'TTTAttributedLabel'
  pod 'Reveal-iOS-SDK'

  target 'ChatKit_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
